#!/usr/bin/env bash
# script used to delete all nonessential files in the directory,
# i.e. image files and other garbage

PROMPT="What kind of file extensions would you like to remove \
(for example: .png)? Type done to exit: "

while true; do
  read -p "$PROMPT" type

  if [[ $type == "done" ]]; then
  	printf "%s\n" "Exiting..."
  	exit 0
  fi

  read -p "What directory do you want to delete from?: " dir
  printf "%s" "WARNING: THIS WILL DELETE ALL $type FILE TYPES FROM THE $dir DIRECTORY."
  read -p "ARE YOU SURE YOU WANT TO CONTINUE? (Y/N): " cont

  eval dir=$dir
  if [[ $cont == Y ]] || [[ $cont == y ]]; then
    for file in "$dir/*$type"; do
      rm $file 2>/dev/null
    done
    printf "%s\n" "Cleanup successful."
  else
    printf "%s\n" "Exiting..."
    exit 0
  fi
done